### ISSUE TITLE
After upgrading to v20.46.0 unable to run on macOS ARM64

### ISSUE THREAD

**Issue by sailingwithsandeep** [uNetworking/uWebSockets.js#1087]
[1]  Error: This version of uWS.js supports only Node.js LTS versions 16, 18 and 20 on (glibc) Linux, macOS and Windows, on Tier 1 platforms (https://github.com/nodejs/node/blob/master/BUILDING.md#platform-list).

```
 Error: dlopen(/Users/userx/Projects/backend/node_modules/uWebSockets.js/uws_darwin_arm64_115.node, 0x0001): symbol not found in flat namespace '_lsquic_conn_get_ctx'
   at /Users/userx/Projects/backend/node_modules/uWebSockets.js/uws.js:22:9
 at Object.<anonymous> (/Users/userx/Projects/backend/node_modules/uWebSockets.js/uws.js:24:3)
     at Module._compile (node:internal/modules/cjs/loader:1376:14)
   at Module._extensions..js (node:internal/modules/cjs/loader:1435:10)
    at Module.load (node:internal/modules/cjs/loader:1207:32)
   at Module._load (node:internal/modules/cjs/loader:1023:12)
   at cjsLoader (node:internal/modules/esm/translators:356:17)
     at ModuleWrap.<anonymous> (node:internal/modules/esm/translators:305:7)
     at ModuleJob.run (node:internal/modules/esm/module_job:218:25)
     at async ModuleLoader.import (node:internal/modules/esm/loader:329:24)
```

**Comment by uNetworkingAB** [comment]
https://github.com/uNetworking/uWebSockets.js/issues/1086

**Comment by uNetworkingAB** [comment]
Normally these symbols would be lazily resolved and crash on use, but looks like that is no longer the case. So I need to fix it properly this time

**Comment by uNetworkingAB** [comment]
It's problematic because GitHub Actions runners are x86_64 and the issue is on ARM64 so smoke testing does not catch it

**Comment by uNetworkingAB** [comment]
fixed in 20.47

**Comment by Vincz** [comment]
Hi @uNetworkingAB, it seems the issue is not fixed.
Trying the latest version (20.47) on a Mac M1, I get the following error:

`dlopen(/project/node_modules/uWebSockets.js/uws_darwin_arm64_115.node, 0x0001): symbol not found in flat namespace '__ZN2v811ArrayBuffer15GetBackingStoreEv`

I'll try an older version and report back.

**Comment by uNetworkingAB** [comment]
```
Hi [@uNetworkingAB](https://github.com/uNetworkingAB), it seems the issue is not fixed.
Trying the latest version (20.47) on a Mac M1, I get the following error:

dlopen(/project/node_modules/uWebSockets.js/uws_darwin_arm64_115.node, 0x0001): symbol not found in flat namespace '__ZN2v811ArrayBuffer15GetBackingStoreEv

I'll try an older version and report back.
```

was this really the case? I have M1 mac and it works without issues for me

**Comment by uNetworkingAB** [comment]
Hahahahahahahahaha

**Comment by uNetworkingAB** [comment]
Maybe I need to add a check for that
