### ISSUE TITLE
Problem with WS socket handshake

### ISSUE THREAD

**Issue by amunhoz** [uNetworking/uWebSockets.js#142]
I'm getting this problem in the browser:

> WebSocket connection to 'wss://xxx.xxxx.com:4447/?param=param' failed: Error during WebSocket handshake: Sent non-empty 'Sec-WebSocket-Protocol' header but no response was received

The connection fails and i cant get anything.

uWebSockets 15.10.0
Chrome 73.0.3683103
node v10.15.3
Ubuntu 18.04

Any clue of what is happening??

**Comment by amunhoz** [comment]
Thanks in advance, by the way.

**Comment by jaamison** [comment]
This is a question about the websocket protocol spec, meaning it has nothing to do with uWS and doesn't really belong here, but just to help give you a push in the right direction: https://stackoverflow.com/a/34202795/5249649

**Comment by alexhultman** [comment]
https://github.com/uNetworking/uWebSockets/issues/851

**Comment by alexhultman** [comment]
> Sent non-empty 'Sec-WebSocket-Protocol' header but no response was received

This is an issue that should be fixed some time. Try and not send any subprotocol.

**Comment by amunhoz** [comment]
It worked after i removed the protocol name from the client side.

**Comment by arpu** [comment]
this still fails when the subprotocol is undefined with this extended client sample 

```
export class Connection extends WebSocket {
    constructor(url, autoConnect = true) {
        super(url, undefined, { connect: autoConnect });
        this._enqueuedCalls = [];
    }
    onOpenCallback(event) {
        super.onOpenCallback();
        this.binaryType = 'arraybuffer';
        if (this._enqueuedCalls.length > 0) {
            for (const [method, args] of this._enqueuedCalls) {
                this[method].apply(this, args);
            }
            // clear enqueued calls.
            this._enqueuedCalls = [];
        }
    }
    send(data) {
        if (this.ws.readyState === WebSocketClient.OPEN) {
            return super.send(msgpack.encode(data));
        }
        else {
            // WebSocket not connected.
            // Enqueue data to be sent when readyState == OPEN
            this._enqueuedCalls.push(['send', [data]]);
        }
    }
}
```

**Comment by alexhultman** [comment]
Fixed
