### ISSUE TITLE
Pub sub, Crashing errors

### ISSUE THREAD

**Issue by danieleratti** [uNetworking/uWebSockets.js#221]
Hello, I'm logging these 4 kind of errors via PM2 few times a day, that are crashing the NodeJs script:

`munmap_chunk(): invalid pointer`
`double free or corruption (!prev)`
`double free or corruption (out)`
`free(): invalid pointer`

...But I can't understand exactly where they come from. I guess they're from the uWebSocket C++ library.

Is there any way to enable more verbosity or investigate where they come from?

**Comment by alexhultman** [comment]
#212

**Comment by alexhultman** [comment]
This should be fixed in v16.2.0

**Comment by danieleratti** [comment]
Just to inform that unfortunately the v16.2.0 still crashes when using a lot the subscribe method (if I don't use it, everything is working fine).

The 3 remaining crashes are:
free(): invalid pointer
double free or corruption (!prev)
double free or corruption (out)

I didn't find any further suggestion yet, but please tell me how may I investigate more, if useful.

**Comment by dioptre** [comment]
Seems like this is a duplicate of closed #212 . Will track here too.

**Comment by alexhultman** [comment]
16.2 definitely fixed the bug of subscribing twice. I'm pretty sure @dioptre had that bug

**Comment by alexhultman** [comment]
@dioptre can you try and get new addresssanitizer reports with 16.2? Make sure to pull all repos

**Comment by dioptre** [comment]
Yes mate will do.

**Comment by dioptre** [comment]
@danieleratti can you please also follow the debug instructions in #212 you might get back to @alexhultman faster than I do as I'm traveling atm

**Comment by dioptre** [comment]
Ok not getting error on duplicates, but not to say that's it. Will report back if I see a crash.

**Comment by dioptre** [comment]
@danieleratti can you please post some code that breaks? Can't seem to reproduce the errors now.

**Comment by danieleratti** [comment]
Thank you @dioptre, I followed the instructions in #212 and I'm running the script with:
```DEBUG=* LD_PRELOAD=/usr/lib/llvm-7/lib/libclang-7.so.1 node index.js```
I'll post the report as soon as it crashes.

**Comment by danieleratti** [comment]
The strange thing is that after compiling the @dioptre debug branch it doesn't crash anymore.
I'll try to compile the master branch of the original repo.

**Comment by danieleratti** [comment]
After one day of running without any crash, I can confirm that it was a human error and the v16.2.0 is working fine

**Comment by alexhultman** [comment]
Great. You didn't really have 16.2 on every node?

**Comment by danieleratti** [comment]
> Great. You didn't really have 16.2 on every node?

Correct

**Comment by alexhultman-2fa** [comment]
Heads up; there's been more crash fixes in latest releases
